# GENERATED BY KOMAND SDK - DO NOT EDIT
from setuptools import setup, find_packages


setup(name="unit_test_demo-rapid7-plugin",
      version="1.0.0",
      description="Show people how to unit test stuff",
      author="rapid7",
      author_email="",
      url="",
      packages=find_packages(),
      install_requires=['komand'],  # Add third-party dependencies to requirements.txt, not here!
      scripts=['bin/icon_unit_test_demo']
      )
