# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class Component:
    DESCRIPTION = "Returns a random number"


class Input:
    pass
    

class Output:
    
    ANSWER = "answer"
    

class RandomNumberInput(komand.Input):
    schema = json.loads("""
   {}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class RandomNumberOutput(komand.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "answer": {
      "type": "integer",
      "title": "Answer",
      "description": "Answer",
      "order": 1
    }
  },
  "required": [
    "answer"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
